rust-lang/std-dev-guide

src/code-considerations/breaking-changes/fundamental.md
src/code-considerations/breaking-changes/new-trait-impls.md
src/code-considerations/safety-and-soundness/generics-and-unsafe.md
src/code-considerations/safety-and-soundness/may-dangle.md
src/code-considerations/using-unstable-lang/const-generics.md
src/code-considerations/using-unstable-lang/specialization.md
src/reviewer-checklist.md
src/tools-and-bots/bors.md
src/tools-and-bots/crater.md
src/tools-and-bots/timer.md

Basically marking every code block with `rust,ignore` to make CI pass for now.

Fixes for mdbook test

---

src/code-considerations/breaking-changes/fundamental.md
src/code-considerations/breaking-changes/new-trait-impls.md

Fixes a warning and a broken link discovered with mdbook-linkcheck

Fixes from Linkcheck

---

src/SUMMARY.md
src/code-considerations/design/must-use.md

cc @rust-lang/libs 
This adds a consideration for the `#[must_use]` attribute, which we get requests to introduce from time-to-time.

Add a consideration for must_use

---

.github/workflows/gh-pages.yml

Our guide is currently available at `rust-lang.github.io/std-dev-guide`, but not at `std-dev-guide.rust-lang.org`.

Also publish cname file

---

src/SUMMARY.md
src/documentation/doc-alias-policy.md
src/documentation/summary.md

Based on discussion in 2021-06-30 libs meeting.

Add a doc alias policy

---

src/SUMMARY.md
src/code-considerations/breaking-changes/prelude.md

As discussed in the libs meeting last week.

Notes on making breaking changes to the prelude

---

src/documentation/safety-comments.md
src/documentation/summary.md

Add SAFETY comments presentation

---

src/SUMMARY.md
src/development/building-and-debugging.md

credit for the hack goes to @nnethercote

How to printf-debug alloc/core

---

src/SUMMARY.md
src/documentation/how-to-write-documentation.md
src/documentation/reviewing-doc-changes.md
src/documentation/summary.md

There are no guidelines on how to write documentation for std/core or how to review documentation updates. This PR is about adding the basics for this.

Add guidelines about writing documentation

---

src/SUMMARY.md
src/documentation/how-to-write-documentation.md

I included first commit from #36.

Fix broken links and invalid code blocks

---

src/documentation/how-to-write-documentation.md

Some updates based on @m-ou-se comments in https://github.com/rust-lang/std-dev-guide/pull/35.

Updates on "how to write documentation"

---

src/feature-lifecycle/stabilization.md

Due to https://github.com/rust-lang/rust/pull/100591 the stabilization process is changed to use `CURRENT_RUSTC_VERSION` instead of spelling out whatever version is currently the latest. This placeholder will be replaced during the release process with the correct version.

Update the library stabilization guide to refer to the new placeholder system

---

src/feature-lifecycle/stabilization.md
src/reviewing.md

Fixes #47
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Replace outdated highfive links

---

src/code-considerations/using-unstable-lang/specialization.md

Document internal specialization attributes

---

src/SUMMARY.md
src/development/perf-benchmarking.md

@jyn514 [requested a guide](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/distributed.20onboarding/near/298499246) how to benchmark std changes.

add a page on optimizations and profiling

---

src/development/building-and-debugging.md

There's an extra hyphen on the "run test and show its output" example command, which took me a while to figure out why it wasn't working (especially since the `--no-capture` does nothing instead of erroring).

fix an extra hyphen

---

src/SUMMARY.md
src/development/feature-lifecycle.md

This PR reworks the workflow for introducing new APIs to the standard library. This is the result of extensive discussion in the 2023 libs meetup.
Major changes include:
- The role of ACPs is now much smaller: their role is to decide whether a feature is suitable/desirable for inclusion in the standard library, rather than to iterate on the exact API design.
- API design exploration happens in community discussions, outside the purview of the libs team. A summary of this discussion should be included when the feature is submitted as a PR to justify the choice of API.
- ACPs are regularly reviewed by the library team in weekly meetings.
cc @rust-lang/libs-api

Rework the feature lifecycle

---

src/SUMMARY.md
src/policy/target-code.md

See discussion in Zulip, including some links to applications of this in practice: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/review.20policy.20for.20tier-3.20.28and.20tier-2.3F.29.20targets

Add policy detailing review procedure for target-specific code

---

src/policy/unsafe-preconditions.md

@ChrisDenton asked me to write up a little explanation about https://github.com/rust-lang/rust/pull/120594 for the library team.
I really don't know what kind of writing or formatting is preferred here, but I'm happy to reshape this if people have opinions.

Add a page for unsafe precondition checks

---

src/SUMMARY.md
src/policy/extension-traits.md

Explain why the standard library uses extension traits rather than `cfg`
